apiVersion: batch/v1
kind: CronJob
metadata:
  name: wikilaeum.backup
  labels:
    name: wikilaeum.backup
    # The toolforge=tool label will cause $HOME and other paths to be mounted from Toolforge
    toolforge: tool
spec:
  schedule: "15 3 * * 1"
  successfulJobsHistoryLimit: 0
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            toolforge: tool
        spec:
          containers:
          - name: backup
            image: docker-registry.tools.wmflabs.org/toolforge-mariadb-sssd-base:latest
            env:
            - name: HOME
              value: /data/project/wikilaeum
            workingDir: /data/project/wikilaeum
            command: [ /bin/sh ]
            args: [ '-c', '/data/project/wikilaeum/db-backup.sh' ]
          restartPolicy: Never
